# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"^\n\x0bItemMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08owner_id\x18\x05 \x01(\x05\"\x91\x01\n\x0bUserMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12 \n\x05items\x18\x07 \x03(\x0b\x32\x11.user.ItemMessage\"B\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"X\n\x11\x43reateItemRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08owner_id\x18\x04 \x01(\x05\"C\n\x10UserListResponse\x12 \n\x05users\x18\x01 \x03(\x0b\x32\x11.user.UserMessage\x12\r\n\x05total\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMMESSAGE']._serialized_start=20
  _globals['_ITEMMESSAGE']._serialized_end=114
  _globals['_USERMESSAGE']._serialized_start=117
  _globals['_USERMESSAGE']._serialized_end=262
  _globals['_CREATEUSERREQUEST']._serialized_start=264
  _globals['_CREATEUSERREQUEST']._serialized_end=330
  _globals['_CREATEITEMREQUEST']._serialized_start=332
  _globals['_CREATEITEMREQUEST']._serialized_end=420
  _globals['_USERLISTRESPONSE']._serialized_start=422
  _globals['_USERLISTRESPONSE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
